In [1]:
import pandas as pd
import numpy as np
import os
import gensim
import nltk

In [2]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /Users/manny/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     /Users/manny/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /Users/manny/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /Users/manny/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /Users/manny/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[n

True

In [3]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [4]:
for file in os.listdir('./data/'):
    print(file)

story1.txt
story2.txt


In [5]:
f = open(r"/Users/manny/Documents/git_repos/Full-stack-GenAI/C7_Apr_12_2026/data/story1.txt",encoding='unicode_escape')

In [6]:
f

<_io.TextIOWrapper name='/Users/manny/Documents/git_repos/Full-stack-GenAI/C7_Apr_12_2026/data/story1.txt' mode='r' encoding='unicode_escape'>

In [7]:
corpus =f.read()

In [8]:
corpus

'Once upon a time, there was a young boy named Arjun who lived in a small town surrounded by hills and rivers. He was very curious about how things worked and always asked questions. His parents often smiled at his curiosity and encouraged him to learn more.\n\nEvery day after school, Arjun would sit with his books and explore different topics. He was especially fascinated by science and technology. He wanted to understand how machines think and whether they could become as intelligent as humans.\n\nOne day, while browsing through an old computer at school, Arjun discovered the concept of artificial intelligence. He read about how machines can learn from data, recognize patterns, and even make decisions. This idea completely amazed him.\n\nHe started imagining a future where machines could help humans solve complex problems. That day, he made a decision that he wanted to become an AI engineer.\n\nArjun began learning programming using free resources. At first, everything seemed difficu

In [9]:
sent_tokenize(corpus)

['Once upon a time, there was a young boy named Arjun who lived in a small town surrounded by hills and rivers.',
 'He was very curious about how things worked and always asked questions.',
 'His parents often smiled at his curiosity and encouraged him to learn more.',
 'Every day after school, Arjun would sit with his books and explore different topics.',
 'He was especially fascinated by science and technology.',
 'He wanted to understand how machines think and whether they could become as intelligent as humans.',
 'One day, while browsing through an old computer at school, Arjun discovered the concept of artificial intelligence.',
 'He read about how machines can learn from data, recognize patterns, and even make decisions.',
 'This idea completely amazed him.',
 'He started imagining a future where machines could help humans solve complex problems.',
 'That day, he made a decision that he wanted to become an AI engineer.',
 'Arjun began learning programming using free resources.',


In [10]:
raw_sent = sent_tokenize(corpus)

In [11]:
for i in raw_sent:
  print(simple_preprocess(i))

['once', 'upon', 'time', 'there', 'was', 'young', 'boy', 'named', 'arjun', 'who', 'lived', 'in', 'small', 'town', 'surrounded', 'by', 'hills', 'and', 'rivers']
['he', 'was', 'very', 'curious', 'about', 'how', 'things', 'worked', 'and', 'always', 'asked', 'questions']
['his', 'parents', 'often', 'smiled', 'at', 'his', 'curiosity', 'and', 'encouraged', 'him', 'to', 'learn', 'more']
['every', 'day', 'after', 'school', 'arjun', 'would', 'sit', 'with', 'his', 'books', 'and', 'explore', 'different', 'topics']
['he', 'was', 'especially', 'fascinated', 'by', 'science', 'and', 'technology']
['he', 'wanted', 'to', 'understand', 'how', 'machines', 'think', 'and', 'whether', 'they', 'could', 'become', 'as', 'intelligent', 'as', 'humans']
['one', 'day', 'while', 'browsing', 'through', 'an', 'old', 'computer', 'at', 'school', 'arjun', 'discovered', 'the', 'concept', 'of', 'artificial', 'intelligence']
['he', 'read', 'about', 'how', 'machines', 'can', 'learn', 'from', 'data', 'recognize', 'patterns',

In [12]:
folder_path = r"/Users/manny/Documents/git_repos/Full-stack-GenAI/C7_Apr_12_2026/data"
story = []
for filename in os.listdir(folder_path):
  file_path=os.path.join(folder_path,filename)
  with open(file_path,encoding='unicode_escape') as f:
    corpus=f.read()
  raw_sent=sent_tokenize(corpus)
  for sent in raw_sent:
    story.append(simple_preprocess(sent))

In [13]:
story

[['once',
  'upon',
  'time',
  'there',
  'was',
  'young',
  'boy',
  'named',
  'arjun',
  'who',
  'lived',
  'in',
  'small',
  'town',
  'surrounded',
  'by',
  'hills',
  'and',
  'rivers'],
 ['he',
  'was',
  'very',
  'curious',
  'about',
  'how',
  'things',
  'worked',
  'and',
  'always',
  'asked',
  'questions'],
 ['his',
  'parents',
  'often',
  'smiled',
  'at',
  'his',
  'curiosity',
  'and',
  'encouraged',
  'him',
  'to',
  'learn',
  'more'],
 ['every',
  'day',
  'after',
  'school',
  'arjun',
  'would',
  'sit',
  'with',
  'his',
  'books',
  'and',
  'explore',
  'different',
  'topics'],
 ['he',
  'was',
  'especially',
  'fascinated',
  'by',
  'science',
  'and',
  'technology'],
 ['he',
  'wanted',
  'to',
  'understand',
  'how',
  'machines',
  'think',
  'and',
  'whether',
  'they',
  'could',
  'become',
  'as',
  'intelligent',
  'as',
  'humans'],
 ['one',
  'day',
  'while',
  'browsing',
  'through',
  'an',
  'old',
  'computer',
  'at',
  'sc

In [14]:
story[0]

['once',
 'upon',
 'time',
 'there',
 'was',
 'young',
 'boy',
 'named',
 'arjun',
 'who',
 'lived',
 'in',
 'small',
 'town',
 'surrounded',
 'by',
 'hills',
 'and',
 'rivers']

In [26]:
custom_model =gensim.models.Word2Vec(
    window=10,
    min_count=1,
    vector_size=150
    
)

In [27]:
custom_model.build_vocab(story)

In [28]:
custom_model.corpus_count

44

In [30]:
custom_model.train(story, total_examples=custom_model.corpus_count, epochs=8)

(2710, 4176)

In [31]:
custom_model.wv["arjun"]

array([ 2.3433405e-03,  2.5202266e-03,  6.6763801e-03, -3.2627934e-03,
       -1.0805755e-03, -4.8542176e-03, -6.7518125e-03, -4.3158792e-03,
       -1.6725553e-03, -3.4639556e-03,  3.7260815e-03, -3.9411262e-03,
        6.8559672e-04,  4.7711111e-04, -3.1082763e-03, -1.4767559e-03,
        6.8053482e-03,  6.0744979e-03, -3.6521582e-03,  6.9590206e-03,
       -4.5451755e-03,  4.0287306e-03, -6.3144963e-04,  3.1919039e-03,
        2.1549717e-03,  4.0233522e-03, -2.7052683e-03,  4.9918517e-03,
        4.3936502e-03, -7.4559576e-03, -4.9155545e-03, -5.1914053e-03,
        1.0974249e-03, -2.8727097e-03, -5.4963520e-03, -5.0210971e-03,
        7.4615772e-03,  1.7026712e-03, -6.2740194e-03, -4.2871558e-03,
        2.0374530e-03, -3.1910839e-03,  2.2541902e-03, -3.2159854e-03,
        2.2804695e-03, -5.4529174e-03,  4.8368662e-03,  2.8239959e-03,
        8.1151817e-04,  1.9533781e-03, -5.8578532e-03,  1.4169789e-03,
       -9.0246781e-04, -5.6722150e-03, -6.4189760e-03, -5.7529222e-04,
      

In [32]:
len(custom_model.wv["arjun"])

150

In [33]:
custom_model.wv["ai"]   

array([ 5.9875492e-03,  5.8387886e-03, -4.0717362e-03,  6.4154441e-04,
       -5.9202360e-03, -4.6809097e-03, -3.2031352e-03,  6.9109323e-03,
       -3.6539389e-03,  4.0651127e-03, -2.8201009e-03, -3.9645527e-03,
        5.1584668e-03,  2.6721330e-03, -2.3501513e-03,  4.7766082e-03,
        3.8715384e-03, -1.4455250e-03,  3.8923312e-03, -5.6727855e-03,
        1.3883749e-03, -6.1677354e-03,  6.0798781e-04, -5.8937701e-03,
       -1.4806425e-03,  6.1356346e-03,  1.7554635e-03, -2.9268018e-05,
       -4.4625071e-03, -6.6891457e-03,  4.5884880e-03, -6.1784382e-03,
        9.9317834e-04,  1.3397671e-03, -1.1732486e-03,  3.8538591e-03,
        2.7126758e-03,  5.1839584e-03,  3.4417058e-03, -5.4472294e-03,
       -2.4502613e-03, -1.7121050e-04, -2.8775905e-03, -3.2450587e-03,
        4.3001012e-03,  5.3346846e-03, -1.7621563e-03,  5.1373499e-03,
       -6.4607211e-03, -4.5369403e-03, -2.7941116e-03,  6.5546269e-03,
        1.0348083e-03,  5.7843176e-04,  3.8843597e-03,  5.3698262e-03,
      

In [35]:
custom_model.wv["AI"]   

KeyError: "Key 'AI' not present"

In [36]:
custom_model.wv["and"]   

array([-1.0490961e-03, -6.5127586e-04,  3.3788702e-03,  5.2831504e-03,
       -6.5780422e-03, -4.6481569e-03,  3.5536955e-03,  9.9153919e-03,
       -5.4638670e-03, -8.6881133e-04,  5.9554260e-03, -8.9739362e-04,
       -5.1690750e-03,  4.5722327e-03, -5.0525283e-03, -2.5800311e-03,
        2.0176319e-03,  5.3109723e-04, -7.2058700e-03, -4.7723697e-03,
        3.3189056e-03,  3.5878641e-03,  7.7011953e-03,  2.5119893e-03,
        4.4155857e-03, -3.3895830e-03, -2.9488276e-03,  2.2174492e-03,
       -6.2626204e-03, -5.0025503e-03, -4.2669536e-03, -8.4224896e-04,
        4.4759880e-03, -6.9059404e-03, -3.4716853e-03, -4.8885349e-04,
        9.5850965e-03, -3.2458492e-03,  1.9552036e-04, -5.4722936e-03,
       -6.3234516e-03,  3.1619447e-03, -8.5274149e-03, -3.7530041e-03,
        1.0842596e-03, -3.4060987e-04, -3.4955563e-03,  5.6934538e-03,
        3.8754682e-03,  6.0330983e-03, -5.6662969e-03,  2.8361094e-03,
       -3.2041483e-03,  1.9556067e-03,  5.4651750e-03, -2.0868757e-03,
      

In [37]:
custom_model.wv["farmers"]   

array([ 2.4644362e-03,  1.0154247e-03,  1.8423513e-03,  5.2379933e-03,
        4.3582921e-03,  2.3759273e-03,  5.2026394e-03, -4.2139790e-03,
        4.5483541e-03,  3.0370594e-03, -3.6240553e-03, -2.7168945e-03,
        3.6387139e-03,  3.8699911e-03, -7.0579471e-03,  4.0350165e-04,
       -1.7388776e-04,  5.8685103e-04,  4.4056168e-03, -4.2732111e-03,
        5.9156185e-03, -6.2475782e-03,  4.8054256e-03,  6.9341199e-03,
       -2.4562238e-03, -6.6025369e-03,  3.5127881e-03, -6.4652283e-03,
       -5.8634146e-03, -1.1341410e-03, -4.2702761e-03,  5.7790074e-03,
        4.8020710e-03, -5.4841763e-05,  4.9172649e-03,  6.8023107e-03,
        4.4759102e-03,  3.1019726e-03,  3.6397788e-03,  3.6348705e-03,
        3.1658064e-03,  4.2029279e-03, -5.5809389e-03,  5.7775411e-03,
        5.8224774e-03,  6.1626933e-03, -5.6378613e-03, -2.4691783e-03,
       -1.0684117e-04,  2.7895472e-03, -5.4879682e-03,  8.5612162e-05,
        3.8900855e-03,  6.6974238e-03, -1.9317671e-03,  1.3678541e-03,
      